services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex 
    privileged: true
    environment: 
      - VERSION=latest
      - TZ=Europe/Berlin
    volumes:
      - .././plex:/config
      - .././data/media:/data/media
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    ports:
      - 32400:32400
    networks:
      - composarr

networks:
  composarr:
    name: composarr