services:
  linuxserver-bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment: 
      - TZ=Europe/Berlin
    volumes:
      - .././bazarr/:/config
      - .././data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - composarr

networks:
  composarr:
    name: composarr