services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp  
      - 8388:8388/tcp  
      - 8388:8388/udp  
      - 8090:8090  
    volumes:
      - .././gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=abc
      - OPENVPN_PASSWORD=abc
      - SERVER_REGIONS=Switzerland
      - TZ=Europe/Berlin 
    restart: unless-stopped
    networks:
      - composarr

networks:
  composarr:
    name: composarr